### ISSUE TITLE
Make the domain/crowdtangle.py working with call in the repository/contents.sync

### ISSUE THREAD

**Issue by InfraFeedback** [feedback-news/feedback-main#123]

**Comment by heloisethero** [comment]
- Create a function in domain/crowdtangle.py to get the relevant data from CT -> Héloïse
- Create a function in repository/crowdtangle.py to create new items in the database from this data -> Héloïse
- Modify the medium model : add the platform name so we can know if a medium is a Facebook account, a Twitter account, etc -> Quan
