### ISSUE TITLE
Create a verdict for a piece of content, to handle FaceBook Flag Feature

### ISSUE THREAD

**Issue by mathieuabeille** [feedback-news/feedback-main#175]
**User Story**
AS Editor
I WANT 
- to declare a potential appearance of a claim to be an appearance
- And create a Facebook Verdict for a piece of Content
SO AS to declare appearances to Facebook

**Context**

Here are the editor workflow that we want to reproduce:

**Step 1:** Determine if the potential appearance (in Content Table) is repeating the claim.
<img width="324" alt="Capture d’écran 2020-11-10 à 16 58 24" src="https://user-images.githubusercontent.com/29702932/98698127-ff853d80-2375-11eb-99c8-502005868a7d.png">
If No,  declare this content is not appearance for this claim in (Links/Appearances) Table. 
If Yes, declare this content is an appearance for this claim in (Links/Appearances) Table.

**Step 2:**We want editors to declare a  facebook verdict for this Appearance. Here are the facebook verdicts: 
- True
- False
- Partly false
- Missing Context
- Satire

We want this verdict to be store in Verdicts Table

<img width="478" alt="Capture d’écran 2020-11-10 à 17 02 55" src="https://user-images.githubusercontent.com/29702932/98700037-0b71ff00-2378-11eb-8575-60f6a43b0411.png">

**Acceptance Criteria**
WHEN I Click on YES to the question "does it repeat the claim?", 
THEN Status for this Content in APPEARANCE Table is Appearance for this claim

WHEN I Click on NO to the question "does it repeat the claim?", 
THEN Status for this Content in APPEARANCE Table is Discarded for this claim

WHEN I answer on "Partly False" to the question "How this should be flagged on Facebook ?", 
THEN a Verdict should be created with Partly False For Facebook value

**Comment by Ledoux** [comment]
Great  !!
Here  https://docs.google.com/presentation/d/1ugihtqJ4wvSIvEogTUx7V7rEXr7Df-8CskG9Jz1zOow/edit#slide=id.ga99551faa4_0_295  

4."webapp testifier pipeline" slide will illustrate what to do for the Step 1 (because all our editors will have also a testifier role that allows them to create links)
5."webapp editor pipeline" slide will illustrate what to do for the Step 2
